server:
  port: 8084
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: commerce-service

  datasource:
    url: jdbc:mysql://localhost:3306/coursecart_commerce_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      catalogService:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 60s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
      enrollmentService:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 60s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
