-- COURSECART FULL TEST DATA SEED
USE coursecart_db;

-- 1. Users
INSERT INTO users (id, name, username, password, role) VALUES 
(1001, 'Admin', 'admin', 'password', 'ADMIN'),
(1002, 'Rahul Sharma', 'rahul_s', 'password', 'USER'),
(1003, 'Priya Patel', 'priya_p', 'password', 'USER'),
(1004, 'Amit Singh', 'amit_s', 'password', 'USER'),
(1005, 'Pooja Verma', 'pooja_v', 'password', 'USER'),
(1006, 'Rohan Gupta', 'rohan_g', 'password', 'USER');

-- 2. Categories
INSERT INTO categories (id, name) VALUES 
(1001, 'Software Engineering'),
(1002, 'Cloud Computing'),
(1003, 'Data Science'),
(1004, 'Artificial Intelligence'),
(1005, 'Web Development');

-- 3. Courses
INSERT INTO courses (id, category_id, title, description, price, original_price, instructor_name, rating, rating_count, is_bestseller, image_url, status) VALUES 
(1001, 1005, 'Java Fundamentals', 'Learn Java from scratch', 49.99, 79.99, 'Prof. John Doe', 4.8, 1500, true, 'assets/courses/Java F.jpg', 'ACTIVE'),
(1003, 1005, 'Angular for Enterprise', 'Master component-driven architecture and state management.', 59.99, 99.99, 'Max S.', 4.9, 3200, true, 'assets/courses/Angular.jpg', 'ACTIVE'),
(1005, 1005, 'Spring Boot Microservices', 'Build scalable backends with Java and Spring Cloud.', 69.99, 129.99, 'Koushikk', 4.8, 5400, true, 'assets/courses/Spring Boot Microservices.jpg', 'ACTIVE'),
(1014, 1001, 'Agile Software Development', 'Skills youll gain: User Story, Agile Software Development...', 39.99, 69.99, 'University of Minnesota', 4.7, 7500, false, 'assets/courses/Agile Software Development.jpg', 'ACTIVE'),
(1015, 1001, 'Software Design and Architecture', 'Skills youll gain: Software Architecture, Model View Controller...', 45.99, 79.99, 'University of Alberta', 4.6, 4000, false, 'assets/courses/Software Design and Architecture.jpg', 'ACTIVE'),
(1017, 1001, 'Microsoft Full-Stack Developer', 'Skills youll gain: Microsoft Copilot, CI/CD, Cascading Style Sheets...', 59.99, 119.99, 'Microsoft', 4.6, 531, false, 'assets/courses/Microsoft Full-Stack Developer.jpg', 'ACTIVE'),
(1018, 1002, 'Introduction to Information Technology and AWS Cloud', 'Skills youll gain: Amazon Web Services, Web Applications...', 39.99, 69.99, 'Amazon Web Services', 4.8, 541, false, 'assets/courses/Introduction to Information Technology and AWS Cloud.jpg', 'ACTIVE'),
(1020, 1002, 'AWS Cloud Technical Essentials', 'Skills youll gain: AWS Identity and Access Management...', 49.99, 79.99, 'Amazon Web Services', 4.8, 6300, false, 'assets/courses/AWS Cloud Technical Essentials.jpg', 'ACTIVE'),
(1021, 1002, 'AWS Cloud Solutions Architect', 'Skills youll gain: AWS Identity and Access Management, Data Lakes...', 89.99, 149.99, 'Amazon Web Services', 4.8, 7100, true, 'assets/courses/AWS Cloud Solutions Architect.jpg', 'ACTIVE'),
(1010, 1003, 'Google Data Analytics', 'Skills youll gain: Data Storytelling, Rmarkdown, Data Visualization...', 49.99, 89.99, 'Google', 4.8, 182000, true, 'assets/courses/Google Data Analytics.jpg', 'ACTIVE'),
(1011, 1003, 'Microsoft Data Analysis with SQL, Excel & Power BI', 'Skills youll gain: Data Visualization, Data Storytelling, Power BI...', 59.99, 99.99, 'Microsoft', 4.6, 1500, false, 'assets/courses/Microsoft Data Analysis with SQL, Excel & Power BI.jpg', 'ACTIVE'),
(1012, 1003, 'Python for Data Science, AI & Development', 'Beginner Course. 5 weeks of study, 3-6 hours per week.', 39.99, 79.99, 'IBM', 4.6, 44000, false, 'assets/courses/Python for Data Science, AI & Development.jpg', 'ACTIVE'),
(1022, 1004, 'Claude Code: Software Engineering with Generative AI Agents', 'Skills youll gain: Claude Code, Anthropic Claude, Multimodal Prompts...', 39.99, 69.99, 'Vanderbilt University', 4.7, 174, false, 'assets/courses/Claude Code Software Engineering.jpg', 'ACTIVE'),
(1023, 1004, 'AI Agents and Agentic AI with Python & Generative AI', 'Skills youll gain: Agentic systems, Generative AI Agents, Agentic Workflows...', 49.99, 89.99, 'Vanderbilt University', 4.6, 475, false, 'assets/courses/AI Agents and Agentic AI with Python & Generative AI.jpg', 'ACTIVE'),
(1024, 1004, 'Fundamentals of Machine Learning and Artificial Intelligence', 'Skills youll gain: Artificial Intelligence and Machine Learning (AI/ML)...', 0.0, 29.99, 'Amazon Web Services', 4.6, 3900, false, 'assets/courses/Fundamentals of Machine Learning and Artificial Intelligence.jpg', 'ACTIVE');

-- 4. Lessons
INSERT INTO lessons (id, course_id, title, content, display_order) VALUES 
(1, 1001, 'Introduction to Java Fundamentals', 'This is the content for Introduction to Java Fundamentals.', 1),
(2, 1001, 'Core Concepts of Java Fundamentals', 'This is the content for Core Concepts of Java Fundamentals.', 2),
(3, 1001, 'Advanced Features in Java Fundamentals', 'This is the content for Advanced Features in Java Fundamentals.', 3),
(4, 1001, 'Building a Project with Java Fundamentals', 'This is the content for Building a Project with Java Fundamentals.', 4),
(5, 1003, 'Introduction to Angular for Enterprise', 'This is the content for Introduction to Angular for Enterprise.', 1),
(6, 1003, 'Core Concepts of Angular for Enterprise', 'This is the content for Core Concepts of Angular for Enterprise.', 2),
(7, 1003, 'Advanced Features in Angular for Enterprise', 'This is the content for Advanced Features in Angular for Enterprise.', 3),
(8, 1003, 'Building a Project with Angular for Enterprise', 'This is the content for Building a Project with Angular for Enterprise.', 4),
(9, 1005, 'Introduction to Spring Boot Microservices', 'This is the content for Introduction to Spring Boot Microservices.', 1),
(10, 1005, 'Core Concepts of Spring Boot Microservices', 'This is the content for Core Concepts of Spring Boot Microservices.', 2),
(11, 1005, 'Advanced Features in Spring Boot Microservices', 'This is the content for Advanced Features in Spring Boot Microservices.', 3),
(12, 1005, 'Building a Project with Spring Boot Microservices', 'This is the content for Building a Project with Spring Boot Microservices.', 4),
(13, 1014, 'Introduction to Agile Software Development', 'This is the content for Introduction to Agile Software Development.', 1),
(14, 1014, 'Core Concepts of Agile Software Development', 'This is the content for Core Concepts of Agile Software Development.', 2),
(15, 1014, 'Advanced Features in Agile Software Development', 'This is the content for Advanced Features in Agile Software Development.', 3),
(16, 1014, 'Building a Project with Agile Software Development', 'This is the content for Building a Project with Agile Software Development.', 4),
(17, 1015, 'Introduction to Software Design and Architecture', 'This is the content for Introduction to Software Design and Architecture.', 1),
(18, 1015, 'Core Concepts of Software Design and Architecture', 'This is the content for Core Concepts of Software Design and Architecture.', 2),
(19, 1015, 'Advanced Features in Software Design and Architecture', 'This is the content for Advanced Features in Software Design and Architecture.', 3),
(20, 1015, 'Building a Project with Software Design and Architecture', 'This is the content for Building a Project with Software Design and Architecture.', 4),
(21, 1017, 'Introduction to Microsoft Full-Stack Developer', 'This is the content for Introduction to Microsoft Full-Stack Developer.', 1),
(22, 1017, 'Core Concepts of Microsoft Full-Stack Developer', 'This is the content for Core Concepts of Microsoft Full-Stack Developer.', 2),
(23, 1017, 'Advanced Features in Microsoft Full-Stack Developer', 'This is the content for Advanced Features in Microsoft Full-Stack Developer.', 3),
(24, 1017, 'Building a Project with Microsoft Full-Stack Developer', 'This is the content for Building a Project with Microsoft Full-Stack Developer.', 4),
(25, 1018, 'Introduction to Introduction to Information Technology and AWS Cloud', 'This is the content for Introduction to Introduction to Information Technology and AWS Cloud.', 1),
(26, 1018, 'Core Concepts of Introduction to Information Technology and AWS Cloud', 'This is the content for Core Concepts of Introduction to Information Technology and AWS Cloud.', 2),
(27, 1018, 'Advanced Features in Introduction to Information Technology and AWS Cloud', 'This is the content for Advanced Features in Introduction to Information Technology and AWS Cloud.', 3),
(28, 1018, 'Building a Project with Introduction to Information Technology and AWS Cloud', 'This is the content for Building a Project with Introduction to Information Technology and AWS Cloud.', 4),
(29, 1020, 'Introduction to AWS Cloud Technical Essentials', 'This is the content for Introduction to AWS Cloud Technical Essentials.', 1),
(30, 1020, 'Core Concepts of AWS Cloud Technical Essentials', 'This is the content for Core Concepts of AWS Cloud Technical Essentials.', 2),
(31, 1020, 'Advanced Features in AWS Cloud Technical Essentials', 'This is the content for Advanced Features in AWS Cloud Technical Essentials.', 3),
(32, 1020, 'Building a Project with AWS Cloud Technical Essentials', 'This is the content for Building a Project with AWS Cloud Technical Essentials.', 4),
(33, 1021, 'Introduction to AWS Cloud Solutions Architect', 'This is the content for Introduction to AWS Cloud Solutions Architect.', 1),
(34, 1021, 'Core Concepts of AWS Cloud Solutions Architect', 'This is the content for Core Concepts of AWS Cloud Solutions Architect.', 2),
(35, 1021, 'Advanced Features in AWS Cloud Solutions Architect', 'This is the content for Advanced Features in AWS Cloud Solutions Architect.', 3),
(36, 1021, 'Building a Project with AWS Cloud Solutions Architect', 'This is the content for Building a Project with AWS Cloud Solutions Architect.', 4),
(37, 1010, 'Introduction to Google Data Analytics', 'This is the content for Introduction to Google Data Analytics.', 1),
(38, 1010, 'Core Concepts of Google Data Analytics', 'This is the content for Core Concepts of Google Data Analytics.', 2),
(39, 1010, 'Advanced Features in Google Data Analytics', 'This is the content for Advanced Features in Google Data Analytics.', 3),
(40, 1010, 'Building a Project with Google Data Analytics', 'This is the content for Building a Project with Google Data Analytics.', 4),
(41, 1011, 'Introduction to Microsoft Data Analysis with SQL, Excel & Power BI', 'This is the content for Introduction to Microsoft Data Analysis with SQL, Excel & Power BI.', 1),
(42, 1011, 'Core Concepts of Microsoft Data Analysis with SQL, Excel & Power BI', 'This is the content for Core Concepts of Microsoft Data Analysis with SQL, Excel & Power BI.', 2),
(43, 1011, 'Advanced Features in Microsoft Data Analysis with SQL, Excel & Power BI', 'This is the content for Advanced Features in Microsoft Data Analysis with SQL, Excel & Power BI.', 3),
(44, 1011, 'Building a Project with Microsoft Data Analysis with SQL, Excel & Power BI', 'This is the content for Building a Project with Microsoft Data Analysis with SQL, Excel & Power BI.', 4),
(45, 1012, 'Introduction to Python for Data Science, AI & Development', 'This is the content for Introduction to Python for Data Science, AI & Development.', 1),
(46, 1012, 'Core Concepts of Python for Data Science, AI & Development', 'This is the content for Core Concepts of Python for Data Science, AI & Development.', 2),
(47, 1012, 'Advanced Features in Python for Data Science, AI & Development', 'This is the content for Advanced Features in Python for Data Science, AI & Development.', 3),
(48, 1012, 'Building a Project with Python for Data Science, AI & Development', 'This is the content for Building a Project with Python for Data Science, AI & Development.', 4),
(49, 1022, 'Introduction to Claude Code: Software Engineering with Generative AI Agents', 'This is the content for Introduction to Claude Code: Software Engineering with Generative AI Agents.', 1),
(50, 1022, 'Core Concepts of Claude Code: Software Engineering with Generative AI Agents', 'This is the content for Core Concepts of Claude Code: Software Engineering with Generative AI Agents.', 2),
(51, 1022, 'Advanced Features in Claude Code: Software Engineering with Generative AI Agents', 'This is the content for Advanced Features in Claude Code: Software Engineering with Generative AI Agents.', 3),
(52, 1022, 'Building a Project with Claude Code: Software Engineering with Generative AI Agents', 'This is the content for Building a Project with Claude Code: Software Engineering with Generative AI Agents.', 4),
(53, 1023, 'Introduction to AI Agents and Agentic AI with Python & Generative AI', 'This is the content for Introduction to AI Agents and Agentic AI with Python & Generative AI.', 1),
(54, 1023, 'Core Concepts of AI Agents and Agentic AI with Python & Generative AI', 'This is the content for Core Concepts of AI Agents and Agentic AI with Python & Generative AI.', 2),
(55, 1023, 'Advanced Features in AI Agents and Agentic AI with Python & Generative AI', 'This is the content for Advanced Features in AI Agents and Agentic AI with Python & Generative AI.', 3),
(56, 1023, 'Building a Project with AI Agents and Agentic AI with Python & Generative AI', 'This is the content for Building a Project with AI Agents and Agentic AI with Python & Generative AI.', 4),
(57, 1024, 'Introduction to Fundamentals of Machine Learning and Artificial Intelligence', 'This is the content for Introduction to Fundamentals of Machine Learning and Artificial Intelligence.', 1),
(58, 1024, 'Core Concepts of Fundamentals of Machine Learning and Artificial Intelligence', 'This is the content for Core Concepts of Fundamentals of Machine Learning and Artificial Intelligence.', 2),
(59, 1024, 'Advanced Features in Fundamentals of Machine Learning and Artificial Intelligence', 'This is the content for Advanced Features in Fundamentals of Machine Learning and Artificial Intelligence.', 3),
(60, 1024, 'Building a Project with Fundamentals of Machine Learning and Artificial Intelligence', 'This is the content for Building a Project with Fundamentals of Machine Learning and Artificial Intelligence.', 4);

-- 5. Orders, Enrollments & Progress
INSERT INTO orders (id, user_id, course_id, amount_paid, order_date, payment_method) VALUES 
(1, 1002, 1022, 39.99, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 17 DAY), 'Credit Card'),
(2, 1002, 1017, 59.99, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 26 DAY), 'PayPal'),
(3, 1002, 1021, 89.99, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 25 DAY), 'Credit Card'),
(4, 1003, 1021, 89.99, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 18 DAY), 'Debit Card'),
(5, 1003, 1023, 49.99, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 21 DAY), 'Credit Card'),
(6, 1003, 1012, 39.99, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 21 DAY)),
(7, 1003, 1020, 49.99, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(8, 1003, 1017, 59.99, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 5 DAY)),
(9, 1004, 1003, 59.99, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 16 DAY)),
(10, 1004, 1001, 49.99, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 15 DAY)),
(11, 1004, 1010, 49.99, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 20 DAY)),
(12, 1005, 1023, 49.99, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 8 DAY)),
(13, 1005, 1001, 49.99, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 22 DAY)),
(14, 1005, 1018, 39.99, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 15 DAY)),
(15, 1005, 1003, 59.99, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 7 DAY)),
(16, 1006, 1017, 59.99, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 10 DAY)),
(17, 1006, 1014, 39.99, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 23 DAY)),
(18, 1006, 1021, 89.99, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 20 DAY)),
(19, 1006, 1023, 49.99, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY));

INSERT INTO enrollments (id, user_id, course_id, enrolled_at) VALUES 
(1, 1002, 1022, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 17 DAY)),
(2, 1002, 1017, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 26 DAY)),
(3, 1002, 1021, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 25 DAY)),
(4, 1003, 1021, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 18 DAY)),
(5, 1003, 1023, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 21 DAY)),
(6, 1003, 1012, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 21 DAY)),
(7, 1003, 1020, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY)),
(8, 1003, 1017, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 5 DAY)),
(9, 1004, 1003, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 16 DAY)),
(10, 1004, 1001, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 15 DAY)),
(11, 1004, 1010, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 20 DAY)),
(12, 1005, 1023, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 8 DAY)),
(13, 1005, 1001, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 22 DAY)),
(14, 1005, 1018, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 15 DAY)),
(15, 1005, 1003, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 7 DAY)),
(16, 1006, 1017, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 10 DAY)),
(17, 1006, 1014, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 23 DAY)),
(18, 1006, 1021, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 20 DAY)),
(19, 1006, 1023, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 2 DAY));

INSERT INTO lesson_progress (id, enrollment_id, lesson_id, is_completed, completed_at) VALUES 
(1, 1, 49, FALSE, NULL),
(2, 1, 50, FALSE, NULL),
(3, 1, 51, FALSE, NULL),
(4, 1, 52, FALSE, NULL),
(5, 2, 21, TRUE, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 25 DAY)),
(6, 2, 22, TRUE, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 25 DAY)),
(7, 2, 23, FALSE, NULL),
(8, 2, 24, FALSE, NULL),
(9, 3, 33, TRUE, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 24 DAY)),
(10, 3, 34, TRUE, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 24 DAY)),
(11, 3, 35, TRUE, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 24 DAY)),
(12, 3, 36, TRUE, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 24 DAY)),
(13, 4, 33, TRUE, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 17 DAY)),
(14, 4, 34, TRUE, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 17 DAY)),
(15, 4, 35, TRUE, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 17 DAY)),
(16, 4, 36, TRUE, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 17 DAY)),
(17, 5, 53, TRUE, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 20 DAY)),
(18, 5, 54, FALSE, NULL),
(19, 5, 55, FALSE, NULL),
(20, 5, 56, FALSE, NULL),
(21, 6, 45, TRUE, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 20 DAY)),
(22, 6, 46, FALSE, NULL),
(23, 6, 47, FALSE, NULL),
(24, 6, 48, FALSE, NULL),
(25, 7, 29, TRUE, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 DAY)),
(26, 7, 30, TRUE, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 DAY)),
(27, 7, 31, TRUE, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 DAY)),
(28, 7, 32, FALSE, NULL),
(29, 8, 21, TRUE, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 4 DAY)),
(30, 8, 22, TRUE, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 4 DAY)),
(31, 8, 23, TRUE, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 4 DAY)),
(32, 8, 24, FALSE, NULL),
(33, 9, 5, TRUE, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 15 DAY)),
(34, 9, 6, TRUE, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 15 DAY)),
(35, 9, 7, TRUE, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 15 DAY)),
(36, 9, 8, TRUE, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 15 DAY)),
(37, 10, 1, TRUE, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 14 DAY)),
(38, 10, 2, FALSE, NULL),
(39, 10, 3, FALSE, NULL),
(40, 10, 4, FALSE, NULL),
(41, 11, 37, TRUE, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 19 DAY)),
(42, 11, 38, TRUE, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 19 DAY)),
(43, 11, 39, FALSE, NULL),
(44, 11, 40, FALSE, NULL),
(45, 12, 53, FALSE, NULL),
(46, 12, 54, FALSE, NULL),
(47, 12, 55, FALSE, NULL),
(48, 12, 56, FALSE, NULL),
(49, 13, 1, TRUE, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 21 DAY)),
(50, 13, 2, FALSE, NULL),
(51, 13, 3, FALSE, NULL),
(52, 13, 4, FALSE, NULL),
(53, 14, 25, TRUE, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 14 DAY)),
(54, 14, 26, TRUE, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 14 DAY)),
(55, 14, 27, FALSE, NULL),
(56, 14, 28, FALSE, NULL),
(57, 15, 5, TRUE, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 6 DAY)),
(58, 15, 6, TRUE, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 6 DAY)),
(59, 15, 7, TRUE, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 6 DAY)),
(60, 15, 8, FALSE, NULL),
(61, 16, 21, TRUE, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 9 DAY)),
(62, 16, 22, TRUE, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 9 DAY)),
(63, 16, 23, TRUE, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 9 DAY)),
(64, 16, 24, TRUE, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 9 DAY)),
(65, 17, 13, TRUE, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 22 DAY)),
(66, 17, 14, TRUE, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 22 DAY)),
(67, 17, 15, FALSE, NULL),
(68, 17, 16, FALSE, NULL),
(69, 18, 33, TRUE, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 19 DAY)),
(70, 18, 34, TRUE, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 19 DAY)),
(71, 18, 35, TRUE, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 19 DAY)),
(72, 18, 36, TRUE, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 19 DAY)),
(73, 19, 53, TRUE, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 DAY)),
(74, 19, 54, TRUE, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 DAY)),
(75, 19, 55, TRUE, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 DAY)),
(76, 19, 56, TRUE, DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 1 DAY));


