server.port=8082

spring.application.name=catalog-service

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/coursecart_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

# JPA Configuration
# Set to 'none' to avoid modifying the manually created database schema
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Consul Configuration
spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.register=true
spring.cloud.consul.discovery.prefer-ip-address=true

# Actuator (Health check for Consul)
management.endpoints.web.exposure.include=health,info

# Exception formatting
server.error.include-message=always
server.error.include-binding-errors=always
